# vim: set ft=yaml ts=2:
---

- name: assertions
  assert:
    that:
      - ansible_distribution == 'CentOS'
      - ansible_distribution_major_version|int == 7

- name: elasticsearch is present
  package:
    name: elasticsearch
    state: present

- name: elasticsearch is started
  service:
    name: elasticsearch
    state: started
    enabled: true
